# TwinGamemode config file

#list of worlds to apply divider and game mode changers
worlds:
  - level:
      name: "world"
      divider:
        #options: vertical (east-west) | horizontal (north south)
        type: vertical
        #options: any coordinate in double form
        coord: 0.0
        #options: positive (east or south) | negative (west or north)
        creative: positive
        #offset when player changes game mode
        offset: 0.0
  - level:
      name: "world_nether"
      divider:
        #options: vertical (east-west) | horizontal (north south)
        type: vertical
        #options: any coordinate in double form
        coord: 0.0
        #options: positive (east or south) | negative (west or north)
        creative: positive
        #offset when player changes game mode
        offset: 0.0


