name: TwinGamemode
version: '${project.version}'
main: me.creeperbomb.twingamemode.TwinGamemode
api-version: 1.17
authors: [ 1creeperbomb ]
description: Split a single world into a survival and creative side
